
script_location: 'dataset/read_dataset.py'
#path: '../datasets/flair_2_toy_dataset'
path: '/raid/aleksispi/master-theses/agnes-malte-spring2024'
norm_path: path_to_norm_stats
#X_path: 'flair_2_toy_aerial'
X_path: 'flair_aerial'
#Y_path: 'flair_2_toy_labels'
Y_path: 'flair_labels'
val_set_size: 0.2
det_crop: False #don't have both det_crop and random_crop on
crop_step_size: 512 #will not be used if random cropping is on
crop_size: 8
random_crop: False
using_priv: True
scale: False

mean: [111.9395, 116.1909, 107.5178, 100.7342, 16.4652] #B is the first channel, then G, then R
std: [52.0012, 45.6826, 44.9341, 39.1731, 29.3537]



#all things that are done on the entire data set, with no probability involved etc., should be done in the read file,
#the rest in transform/aug