
script_location: 'dataset/read_dataset.py'
#path: '../datasets/flair_2_toy_dataset'
path: '/Exjobb RISE/mleo_masters'
norm_path: path_to_norm_stats
#X_path: 'flair_2_toy_aerial'
X_path: 'flair_aerial'
#Y_path: 'flair_2_toy_labels'
Y_path: 'flair_labels'
val_set_size: 0.2
crop: False
crop_size: 200
crop_step_size: 100
using_priv: False
scale: 

#all things that are done on the entire data set, with no probability involved etc., should be done in the read file,
#the rest in transform/aug