
script_location: 'dataset/read_dataset.py'
#path: '../datasets/flair_2_toy_dataset'
path: '../datasets/flair'
norm_path: path_to_norm_stats
#X_path: 'flair_2_toy_aerial'
X_path: 'flair_aerial'
#Y_path: 'flair_2_toy_labels'
Y_path: 'flair_labels'
senti_path: 'flair_sen'

dataset_size: 0.05
val_set_size: 0.2
det_crop: False #don't have both det_crop and random_crop on
crop_step_size: 512 #will not be used if random cropping is on
crop_size: 512 #128
random_crop: False
using_priv: True
scale: False
using_senti: True
senti_size: 20 #one-sided, so 40 in total

mean: [113.7693, 118.0902, 109.2753, 102.3808, 16.7343] #B is the first channel, then G, then R (only on train, not val)
std: [52.3925, 46.0153, 45.2657, 39.4576, 29.5914]
mean_senti: [126.5045, 127.2261, 127.4363, 127.2859, 127.0794, 127.1531, 127.1539, 127.0784, 127.0547, 127.1054]
std_senti: [44.7545, 44.3896, 44.5939, 43.8597, 43.7466, 43.6991, 43.6935, 43.6990, 43.7319, 43.8538]

#all things that are done on the entire data set, with no probability involved etc., should be done in the read file,
#the rest in transform/aug